export const tasks = [
  {
    no: 1,
    taskName: 'Create user interface designs.',
    createdDate: 'June 01, 2024',
    numberOfTasks: '4/8',
    deadline: 'June 10, 2024',
    project: '2',
    assignee: 'assets/images/users/user-11.jpg',
    checked: true,
  },
  {
    no: 2,
    taskName: 'Test new features and updates.',
    createdDate: 'July 15, 2023',
    numberOfTasks: '1/5',
    deadline: 'September 10, 2023',
    project: '4',
    assignee: 'assets/images/users/user-12.jpg',
    checked: false,
  },
  {
    no: 3,
    taskName: 'Optimize database queries',
    createdDate: 'August 12, 2023',
    numberOfTasks: '0/4',
    deadline: 'December 08, 2023',
    project: '1',
    assignee: 'assets/images/users/user-13.jpg',
    checked: false,
  },
  {
    no: 4,
    taskName: 'Develop API endpoints.',
    createdDate: 'September 5, 2023',
    numberOfTasks: '2/6',
    deadline: 'February 25, 2024',
    project: '5',
    assignee: 'assets/images/users/user-14.jpg',
    checked: false,
  },
  {
    no: 5,
    taskName: 'Conduct user feedback surveys',
    createdDate: 'October 1, 2023',
    numberOfTasks: '4/10',
    deadline: 'November 29, 2023',
    project: '3',
    assignee: 'assets/images/users/user-15.jpg',
    checked: true,
  },
  {
    no: 6,
    taskName: 'Review codebase for security vulnerabilities',
    createdDate: 'May 15, 2023',
    numberOfTasks: '5/8',
    deadline: 'December 08, 2023',
    project: '6',
    assignee: 'assets/images/users/user-10.jpg',
    checked: true,
  },
]

export const transaction = [
  {
    date: '01 January',
    quantity: 45,
    change: '+$70',
    total: '$78,000',
    changeClass: 'text-success',
  },
  {
    date: '05 February',
    quantity: 35,
    change: '-$48',
    total: '$18,000',
    changeClass: 'text-danger',
  },
  {
    date: '15 March',
    quantity: 28,
    change: '-$31',
    total: '$15,000',
    changeClass: 'text-danger',
  },
  {
    date: '06 April',
    quantity: 38,
    change: '+$58',
    total: '$125,000',
    changeClass: 'text-success',
  },
  {
    date: '08 May',
    quantity: 42,
    change: '+$65',
    total: '$80,000',
    changeClass: 'text-success',
  },
  {
    date: '25 December',
    quantity: 39,
    change: '-$41',
    total: '$73,000',
    changeClass: 'text-danger',
  },
  {
    date: '18 January',
    quantity: 45,
    change: '+$74',
    total: '$72,500',
    changeClass: 'text-success',
  },
  {
    date: '09 September',
    quantity: 29,
    change: '-$25',
    total: '$23,000',
    changeClass: 'text-danger',
  },
]

export const latestTransaction = [
  {
    transactionType: 'Salary payment',
    icon: 'mdi-credit-card-outline',
    person: {
      name: 'Jenny Wilson',
      avatar: 'assets/images/users/user-12.jpg',
    },
    date: 'February 14, 2024',
    amount: '$449.51',
    status: {
      text: 'Completed',
      icon: 'check-circle',
      iconClass: 'text-primary',
    },
  },
  {
    transactionType: 'Office Manage',
    icon: 'mdi-cash',
    person: {
      name: 'Jenny Wilson',
      avatar: 'assets/images/users/user-15.jpg',
    },
    date: 'January 25, 2024',
    amount: '$870.95',
    status: {
      text: 'Completed',
      icon: 'check-circle',
      iconClass: 'text-primary',
    },
  },
  {
    transactionType: 'Client payment',
    icon: 'mdi-account-outline',
    person: {
      name: 'Cameron Williamson',
      avatar: 'assets/images/users/user-13.jpg',
    },
    date: 'March 16, 2024',
    amount: '$687.85',
    status: {
      text: 'On progress',
      icon: 'loader',
      iconClass: 'text-warning',
    },
  },
  {
    transactionType: 'Investment',
    icon: 'mdi-hand-coin-outline',
    person: {
      name: 'Jenny Wilson',
      avatar: 'assets/images/users/user-11.jpg',
    },
    date: 'June 20, 2024',
    amount: '$528.18',
    status: {
      text: 'On progress',
      icon: 'loader',
      iconClass: 'text-warning',
    },
  },
  {
    transactionType: 'Marketing',
    icon: 'mdi-chart-box-plus-outline',
    person: {
      name: 'Esther Howard',
      avatar: 'assets/images/users/user-14.jpg',
    },
    date: 'July 16, 2024',
    amount: '$449.51',
    status: {
      text: 'Completed',
      icon: 'check-circle',
      iconClass: 'text-primary',
    },
  },
  {
    transactionType: 'Salary payment',
    icon: 'mdi-credit-card-outline',
    person: {
      name: 'Darlene Robertson',
      avatar: 'assets/images/users/user-3.jpg',
    },
    date: 'May 27, 2024',
    amount: '$478.51',
    status: {
      text: 'Completed',
      icon: 'check-circle',
      iconClass: 'text-primary',
    },
  },
]
