export const recentOrder = [
  {
    order_id: '#3413',
    customer_name: 'Richard Dom',
    customer_email: 'richard@api.com',
    items: 82,
    total: '$480.00',
    created: 'August 09, 2023',
    modified: 'August 18, 2023',
    status: 'Delivered',
    status_class: 'bg-primary-subtle text-primary',
    img: 'assets/images/users/user-12.jpg',
  },
  {
    order_id: '#4125',
    customer_name: 'Randal Dare',
    customer_email: 'randal@dotcom.com',
    items: 93,
    total: '$568.00',
    created: 'January 19, 2023',
    modified: 'March 09, 2023',
    status: 'Delivered',
    status_class: 'bg-primary-subtle text-primary',
    img: 'assets/images/users/user-11.jpg',
  },
  {
    order_id: '#6532',
    customer_name: 'Bickle Bob',
    customer_email: 'bicklebob@dotcom.com',
    items: 56,
    total: '$398.00',
    created: 'April 25, 2023',
    modified: 'June 21, 2023',
    status: 'Cancelled',
    status_class: 'bg-danger-subtle text-danger',
    img: 'assets/images/users/user-13.jpg',
  },
  {
    order_id: '#7405',
    customer_name: 'Emma Wilson',
    customer_email: 'emmawilson@dotcom.com',
    items: 68,
    total: '$652.00',
    created: 'September 24, 2023',
    modified: 'November 13, 2023',
    status: 'Pending',
    status_class: 'bg-info-subtle text-info',
    img: 'assets/images/users/user-14.jpg',
  },
  {
    order_id: '#4526',
    customer_name: 'Hugh Jackma',
    customer_email: 'hughjackma@dotcom.com',
    items: 52,
    total: '$746.00',
    created: 'July 28, 2023',
    modified: 'August 21, 2023',
    status: 'Shipped',
    status_class: 'bg-warning-subtle text-warning',
    img: 'assets/images/users/user-15.jpg',
  },
  {
    order_id: '#1054',
    customer_name: 'Angelina Hose',
    customer_email: 'angelinahose@dotcom.com',
    items: 45,
    total: '$205.00',
    created: 'June 09, 2023',
    modified: 'August 25, 2023',
    status: 'Pending',
    status_class: 'bg-info-subtle text-info',
    img: 'assets/images/users/user-12.jpg',
  },
]
